services:
  api:
    image: proseim/prose-pod-api
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./database.db:/database.db
      - "${PROSE_CONFIG_FILE:-./Prose.toml}:/Prose.toml"
      - ./Rocket.toml:/Rocket.toml
      - ./server/pod/etc/prosody/:/etc/prosody/
    networks:
      prose-network:
        aliases:
          - prose-pod-api
    env_file:
      - "${ENV_FILE:-.env}"

  server:
    image: proseim/prose-pod-server
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5582:5582"
    volumes:
      - ./server/pod/etc/prosody/:/etc/prosody/
      - ./server/pod/var/lib/prosody/:/var/lib/prosody/
    networks:
      prose-network:
        aliases:
          - prose-pod-server
    env_file:
      - "${ENV_FILE:-.env}"
    entrypoint: >
      sh -c "cp etc/prosody/prosody.cfg.lua.initial etc/prosody/prosody.cfg.lua && prosody"

networks:
  prose-network: {}
