services:
  api:
    image: "${PROSE_POD_API_IMAGE:-proseim/prose-pod-api:${PROSE_POD_API_IMAGE_TAG:-${DEFAULT_DOCKER_TAG:-0.6.0}}}"
    ports:
      - "8080:8080"
    volumes:
      - "${DATABASE_PATH-./database.sqlite}:/database.sqlite"
      - "${PROSE_CONFIG_FILE-./Prose.toml}:/Prose.toml"
      - "${SERVER_ROOT:-}/etc/prosody/:/etc/prosody/"
    networks:
      prose-network:
        aliases:
          - prose-pod-api
    environment:
      - RUST_LOG_STYLE=always
    env_file:
      - "${ENV_FILE-.env}"

  server:
    image: "${PROSE_POD_SERVER_IMAGE:-proseim/prose-pod-server:${PROSE_POD_SERVER_IMAGE_TAG:-${DEFAULT_DOCKER_TAG:-0.3.4}}}"
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5582:5582"
    volumes:
      - "${SERVER_ROOT:-}/etc/prosody/:/etc/prosody/"
      - "${SERVER_ROOT:-}/var/lib/prosody/:/var/lib/prosody/"
    networks:
      prose-network:
        aliases:
          - prose-pod-server
          - prose-pod-server-admin
    env_file:
      - "${ENV_FILE-.env}"
    entrypoint: >
      sh -c "cp /etc/prosody/prosody.bootstrap.cfg.lua /etc/prosody/prosody.cfg.lua && prosody"

networks:
  prose-network: {}
