services:
  api:
    image: proseim/prose-pod-api:latest
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - "${DATABASE_PATH-./database.sqlite}:/database.sqlite"
      - "${PROSE_CONFIG_FILE-./Prose.toml}:/Prose.toml"
      - "${ROCKET_CONFIG_FILE-./Rocket.toml}:/Rocket.toml"
      - "${SERVER_ROOT:-}/etc/prosody/:/etc/prosody/"
    networks:
      prose-network:
        aliases:
          - prose-pod-api
    environment:
      - RUST_LOG_STYLE=always
    env_file:
      - "${ENV_FILE-.env}"

  server:
    image: proseim/prose-pod-server:latest
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5582:5582"
    volumes:
      - "${SERVER_ROOT:-}/etc/prosody/:/etc/prosody/"
      - "${SERVER_ROOT:-}/var/lib/prosody/:/var/lib/prosody/"
    networks:
      prose-network:
        aliases:
          - prose-pod-server
          - prose-pod-server-admin
    env_file:
      - "${ENV_FILE-.env}"
    entrypoint: >
      sh -c "cp /etc/prosody/prosody.cfg.lua.initial /etc/prosody/prosody.cfg.lua && prosody"

networks:
  prose-network: {}
