name: prose

services:
  # https://github.com/prose-im/prose-app-web
  app:
    image: ${PROSE_APP_WEB_IMAGE:-proseim/prose-app-web}:${PROSE_APP_WEB_VERSION:-0.11.0}
    user: ${PROSE_APP_WEB_UID:-${PROSE_UID-0}}:${PROSE_APP_WEB_GID:-${PROSE_GID-0}}
    depends_on: [server]
    ports:
      - "${PROSE_APP_WEB_PORT:-8080}:8080"
    tty: "${PROSE_APP_WEB_IS_TTY:-${PROSE_POD_IS_TTY:-false}}"

  # https://github.com/prose-im/prose-pod-dashboard
  dashboard:
    image: ${PROSE_POD_DASHBOARD_IMAGE:-proseim/prose-pod-dashboard}:${PROSE_POD_DASHBOARD_VERSION:-0.0.1}
    user: ${PROSE_POD_DASHBOARD_UID:-${PROSE_UID-0}}:${PROSE_POD_DASHBOARD_GID:-${PROSE_GID-0}}
    depends_on: [api]
    ports:
      - "${PROSE_POD_DASHBOARD_PORT:-3030}:3030"
    networks:
      prose-network:
        aliases:
          - prose-pod-dashboard
    tty: "${PROSE_POD_DASHBOARD_IS_TTY:-${PROSE_POD_IS_TTY:-false}}"

  # https://github.com/prose-im/prose-pod-api
  api:
    image: ${PROSE_POD_API_IMAGE:-proseim/prose-pod-api}:${PROSE_POD_API_VERSION:-0.14.1}
    user: ${PROSE_POD_API_UID:-${PROSE_UID-1001}}:${PROSE_POD_API_GID:-${PROSE_GID-1001}}
    depends_on: [server]
    volumes:
      - "${PROSE_POD_API_DATA_DIR:-/var/lib/prose-pod-api/}:/var/lib/prose-pod-api/"
      # NOTE: `/etc/prose-pod-api` cannot be read-only because we need to
      #   override it when doing a factory reset (and only then).
      - "${PROSE_POD_API_CONFIG_DIR:-/etc/prose-pod-api/}:/etc/prose-pod-api/"
      - "${PROSODY_CONFIG_DIR:-/etc/prosody/}:/etc/prosody/"
    networks:
      prose-network:
        aliases:
          - prose-pod-api
    env_file: "${PROSE_POD_API_ENV_FILE:-${PROSE_ENV_FILE:-/etc/prose/prose.env}}"
    tty: "${PROSE_POD_API_IS_TTY:-${PROSE_POD_IS_TTY:-false}}"

  # https://github.com/prose-im/prose-pod-server
  server:
    image: ${PROSE_POD_SERVER_IMAGE:-proseim/prose-pod-server}:${PROSE_POD_SERVER_VERSION:-0.3.19}
    user: ${PROSE_POD_SERVER_UID:-${PROSE_UID-1001}}:${PROSE_POD_SERVER_GID:-${PROSE_GID-1001}}
    volumes:
      - "${PROSODY_CONFIG_DIR:-/etc/prosody/}:/etc/prosody/"
      - "${PROSODY_DATA_DIR:-/var/lib/prosody/}:/var/lib/prosody/"
    # NOTE: See [Port and network configuration – Prosody IM](https://prosody.im/doc/ports).
    ports:
      # [Client connections](https://prosody.im/doc/modules/mod_c2s).
      - "${PROSE_POD_SERVER_INTERFACE_C2S:-0.0.0.0}:${PROSE_POD_SERVER_PORT_C2S:-5222}:5222"
      # [Server-to-server connections](https://prosody.im/doc/modules/mod_s2s).
      - "${PROSE_POD_SERVER_INTERFACE_S2S:-0.0.0.0}:${PROSE_POD_SERVER_PORT_S2S:-5269}:5269"
      # [HTTP](https://prosody.im/doc/http).
      - "${PROSE_POD_SERVER_INTERFACE_HTTP:-127.0.0.1}:${PROSE_POD_SERVER_PORT_HTTP:-5280}:5280"
      # [HTTPS](https://prosody.im/doc/http).
      - "${PROSE_POD_SERVER_INTERFACE_HTTPS:-0.0.0.0}:${PROSE_POD_SERVER_PORT_HTTPS:-5281}:5281"
    networks:
      prose-network:
        aliases:
          - prose-pod-server
          - prose-pod-server-admin
    env_file: "${PROSODY_ENV_FILE:-${PROSE_ENV_FILE:-/etc/prose/prose.env}}"
    entrypoint: >
      sh -c "cp /usr/share/prose/prosody.bootstrap.cfg.lua /etc/prosody/prosody.cfg.lua && prosody"
    tty: "${PROSE_POD_SERVER_IS_TTY:-${PROSE_POD_IS_TTY:-false}}"

networks:
  prose-network:
    enable_ipv6: true
