# Prose Pod API
# REST API for administrating a Prose Pod
# Configuration file
# Example: https://github.com/prose-im/prose-pod-api/blob/master/Prose-example.toml
# All keys: https://github.com/prose-im/prose-pod-api/blob/master/service/src/config/mod.rs

# See https://docs.prose.org/references/pod-config/#brandingconfig.
[branding]
company_name = "{your_company_name}"

# See https://docs.prose.org/references/pod-config/#notifyemailconfig.
[notify.email]
pod_address = "prose@{smtp_host}"

smtp_host = "{smtp_host}"
smtp_port = 587 # Change if needed
smtp_username = "{smtp_username}"
smtp_password = "{smtp_password}"
smtp_encrypt = false # Change if needed
