# Prose configuration file
# Documentation: https://docs.prose.org/references/pod-config

# See https://docs.prose.org/references/pod-config/#brandingconfig.
[branding]
company_name = "{company_name}"

# See https://docs.prose.org/references/pod-config/#serverconfig.
[server]
domain = "{your_domain}" # Once set, cannot be changed.

# See https://docs.prose.org/references/pod-config/#podconfig.
[pod]
address = { domain = "{pod_domain}" }

# See https://docs.prose.org/references/pod-config/#notifyemailconfig.
[notifiers.email]
smtp_host = "{smtp_host}"
smtp_port = {smtp_port}
smtp_username = "{smtp_username}"
smtp_password = "{smtp_password}"
smtp_encrypt = {smtp_encrypt}
