#!/usr/bin/env bash

##
# This file is part of prose-pod-system
#
# Copyright 2025–2026, Prose Foundation
# SPDX-License-Identifier: MPL-2.0
#
# Authors:
# - 2025–2026, Rémi Bardon <remi@remibardon.name>
##

set -e


# ===== CONSTANTS =====

: ${SELF:="$(basename $0)"}

: ${REPOSITORY_ROOT:="$(realpath "$(dirname "$0")"/..)"};
VERSION_FILE="${REPOSITORY_ROOT:?}"/VERSION

VERSION="$(cat "${VERSION_FILE:?}")"


# ===== HELPER FUNCTIONS =====

: ${SCRIPTS_DIR:="$(dirname $0)"}
: ${BASH_TOOLBOX:="${SCRIPTS_DIR:?}"/bash-toolbox}
for util in colors edo log; do
  source "${BASH_TOOLBOX:?}/${util:?}.sh"
done
source "${SCRIPTS_DIR:?}"/tools/find-replace-versions.sh

description() {
	cat <<EOF
${Bold}Creates a new Prose Pod release.${Bold_Off}

This script bumps the version number, then adds and pushes a tag to origin.
EOF
}

usage() {
	cat <<EOF
$(format_title 'Usage:')
  $(format_command "${SELF:?}") $(format_arg 'major|minor|patch') $(format_opt_arg '--help')
EOF
}

help() {
	printf "$(description)\n"
	echo ''
	printf "$(usage)\n"
	exit 0
}

commit_message() {
	cat <<EOF
${NEW_VERSION:?}

Internal versions:

- App: $(find_version_app)
- Dashboard: $(find_version_dashboard)
- API: $(find_version_api)
- Server: $(find_version_server)
EOF
}


# ===== ARGUMENT PARSING =====

VERSION_COMPONENTS=($(echo "${VERSION:?}" | tr '.' ' '))

# Process non-positional arguments.
ARGS_=()
for arg in "$@"; do
	case $arg in
		--force) FORCE=1 ;;
		--help) help ;;
		--dry-run) export DRY_RUN=1 ;;
		--debug) export LOG_LEVEL=debug ;;
		--trace) export LOG_LEVEL=trace ;;
		*) ARGS_+=("$arg") ;;
	esac
done
# Update command args so we can then list test names.
set -- "${ARGS_[@]}"
unset ARGS_

# Process positional arguments.
case "$1" in
	major)
		VERSION_COMPONENTS[0]=$(( VERSION_COMPONENTS[0] + 1 ))
		VERSION_COMPONENTS[1]=0
		VERSION_COMPONENTS[2]=0
		;;
	minor)
		VERSION_COMPONENTS[1]=$(( VERSION_COMPONENTS[1] + 1 ))
		VERSION_COMPONENTS[2]=0
		;;
	patch)
		VERSION_COMPONENTS[2]=$(( VERSION_COMPONENTS[2] + 1 ))
		;;
	'')
		error "Expected at least one positional argument ($(format_code major), $(format_code minor) or $(format_code patch))."
		info "$(usage)"
		die
		;;
	*) error "Unknown argument: $(format_code "${1}")."; echo "$(usage)"; die ;;
esac
# Skip first argument now that it’s processed.
shift 1

for arg in "$@"; do
	case $arg in
		*) error "Unknown argument: $(format_code "${arg}")."; echo "$(usage)"; die ;;
	esac
done


# ===== MAIN LOGIC =====

# Ensure there are no uncommitted changes.
if [ -z "$FORCE" ]; then
	git diff-index --quiet HEAD || die "Your index contains uncommitted changes. Please commit or stash them before creating a release."
fi

# Convert the new version to a string.
NEW_VERSION=$(echo "${VERSION_COMPONENTS[*]}" | tr ' ' '.')

# Pull remote.
GIT_BRANCH="$(git branch --show-current)"
info "Pulling origin…"
edo git pull origin "${GIT_BRANCH:?}"

# Log some useful info.
info "Pod version: $(fg_yellow "${VERSION:?}") -> $(fg_green "${NEW_VERSION:?}")"
if git rev-list --quiet "${VERSION:?}"..HEAD; then
	die "No new commit since last version ($(format_code "${VERSION:?}")). This release is useless."
else
	info "New commits:"
	git --no-pager log --reverse --no-merges \
		--format="- %C(auto)%h %s %C(green)(%ad)%C(reset)" --date=short --color \
		"${VERSION:?}"..HEAD
fi

# Update version number in files.
info "Changing version number in $(format_code "${VERSION_FILE:?}")…"
edo echo "${NEW_VERSION:?}" \> "${VERSION_FILE:?}"

# Create & push a new git tag.
COMMIT_MESSAGE="$(commit_message)"
info "Committing changes…"
edo git add "${VERSION_FILE:?}"
edo git commit -m "${COMMIT_MESSAGE:?}"
info "Creating tag…"
edo git tag "${NEW_VERSION:?}" -m "${COMMIT_MESSAGE:?}"
info "Pushing tag…"
edo git push --atomic origin "${GIT_BRANCH:?}" "${NEW_VERSION:?}"

success "Successfully created and pushed tag '${NEW_VERSION:?}'"
