#!/bin/bash

##
#  This file is part of prose-pod-system
#
#  Copyright 2025, Prose Foundation
##

COMPOSE_FILE=compose.yaml

set -e

: ${SELF:="$(basename $0)"}

Color_Off='\033[0m'
Green='\033[0;32m'
Yellow='\033[0;33m'
Cyan='\033[0;36m'
BRed='\033[1;31m'

error() {
	echo -e "${BRed:?}${@:?"Must pass a message"}${Color_Off:?}" >&2
}
die() {
	[[ $# == 0 ]] || error "${@}"
	exit 1
}
usage() {
	echo "Usage: ${SELF:?} [dashboard=X.Y.Z] [api=X.Y.Z] [server=X.Y.Z]"
}
help() {
	usage
	exit 0
}

# A simplified `sed` command that works on both macOS and Linux.
replace() {
	local in_place
	[[ "$1" == "-i" ]] && { in_place=1; shift 1; }

	if [[ "$(uname)" == "Darwin" ]]; then
		(( $in_place )) && sed -i '' -E "$@" || sed -E "$@"
	else
		sed ${in_place:+-i} -E "$@"
	fi
}
replace_version() {
	local regex="${1:?}" replace="${2:?}" file="${3:?}"
	local pattern='s/'"${regex}"'/\1'"${replace}"'\3/'

	replace -i "$pattern" "$file"
}
find_version() {
	local regex="${1:?}"
	replace -n 's/.*'"${regex}"'.*/\2/p' "${COMPOSE_FILE:?}"
}

for arg in "$@"; do
	case $arg in
		dashboard=*) NEW_DASHBOARD_TAG="${arg#'dashboard='}" ;;
		api=*) NEW_API_TAG="${arg#'api='}" ;;
		server=*) NEW_SERVER_TAG="${arg#'server='}" ;;
		--help) help ;;
		*) error 'Unknown argument: `'"$arg"'`.'; echo "$(usage)"; die ;;
	esac
done

# `:` blocks the greedy `+` from eating the `:-` prefix and `}` the suffix.
# Otherwise, allow pretty much any name, there's no reason to enforce a pattern here.
DOCKER_TAG_REGEX='[^:}]+'

if [[ $# == 0 ]]; then
	echo 'Since you didn’t pass any version to update, you might be wondering'
	echo -e 'what the current versions are. Here it is:\n'
fi

DASHBOARD_REGEX='(PROSE_POD_DASHBOARD_VERSION:-)('"${DOCKER_TAG_REGEX:?}"')(\}+)'
OLD_DASHBOARD_TAG="$(find_version "${DASHBOARD_REGEX:?}")"
if [[ -n "${NEW_DASHBOARD_TAG}" ]]; then
	echo -e "Dashboard: ${Yellow:?}${OLD_DASHBOARD_TAG:?}${Color_Off:?} -> ${Green:?}${NEW_DASHBOARD_TAG:?}${Color_Off:?}"
else
	echo -e "Dashboard: ${Cyan:?}${OLD_DASHBOARD_TAG:?}${Color_Off:?}"
fi

API_REGEX='(PROSE_POD_API_VERSION:-)('"${DOCKER_TAG_REGEX:?}"')(\}+)'
OLD_API_TAG="$(find_version "${API_REGEX:?}")"
if [[ -n "${NEW_API_TAG}" ]]; then
	echo -e "API: ${Yellow:?}${OLD_API_TAG:?}${Color_Off:?} -> ${Green:?}${NEW_API_TAG:?}${Color_Off:?}"
else
	echo -e "API: ${Cyan:?}${OLD_API_TAG:?}${Color_Off:?}"
fi

SERVER_REGEX='(PROSE_POD_SERVER_VERSION:-)('"${DOCKER_TAG_REGEX:?}"')(\}+)'
OLD_SERVER_TAG="$(find_version "${SERVER_REGEX:?}")"
if [[ -n "${NEW_SERVER_TAG}" ]]; then
	echo -e "Server: ${Yellow:?}${OLD_SERVER_TAG:?}${Color_Off:?} -> ${Green:?}${NEW_SERVER_TAG:?}${Color_Off:?}"
else
	echo -e "Server: ${Cyan:?}${OLD_SERVER_TAG:?}${Color_Off:?}"
fi

if [[ $# == 0 ]]; then
	echo -e '\nIf you didn’t know how to use the command, here’s how:'
	help
fi

read -p "Proceed? [y/N]: " ok
[[ "$ok" =~ ^[Yy]$ ]] || exit 1

if [[ -n "${NEW_DASHBOARD_TAG}" ]]; then
	replace_version "${DASHBOARD_REGEX:?}" "${NEW_DASHBOARD_TAG:?}" "${COMPOSE_FILE:?}"
fi
if [[ -n "${NEW_API_TAG}" ]]; then
	replace_version "${API_REGEX:?}" "${NEW_API_TAG:?}" "${COMPOSE_FILE:?}"
fi
if [[ -n "${NEW_SERVER_TAG}" ]]; then
	replace_version "${SERVER_REGEX:?}" "${NEW_SERVER_TAG:?}" "${COMPOSE_FILE:?}"
fi
